name: copilot-deploy-environment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      WEBAPI_ARTIFACT_NAME:
        required: true
        type: string
      MEMORYPIPELINE_ARTIFACT_NAME:
        required: true
        type: string
      PLUGINS_ARTIFACT_NAME:
        required: true
        type: string
    outputs:
      backend-host:
        description: "Host on which backend runs"
        value: ${{jobs.deploy-backend.outputs.backend-host}}

permissions:
  contents: read
  id-token: write

jobs:
  deploy-infra:
    uses: ./.github/workflows/copilot-deploy-infra.yml
    with:
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}

  deploy-backend:
    needs: [deploy-infra]
    uses: ./.github/workflows/copilot-deploy-backend.yml
    with:
      ARTIFACT_NAME: ${{inputs.WEBAPI_ARTIFACT_NAME}}
      DEPLOYMENT_NAME: ${{needs.deploy-infra.outputs.deployment-id}}
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}

  deploy-memorypipeline:
    needs: [deploy-infra]
    uses: ./.github/workflows/copilot-deploy-memorypipeline.yml
    with:
      ARTIFACT_NAME: ${{inputs.MEMORYPIPELINE_ARTIFACT_NAME}}
      DEPLOYMENT_NAME: ${{needs.deploy-infra.outputs.deployment-id}}
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}

  deploy-plugins:
    needs: [deploy-infra]
    uses: ./.github/workflows/copilot-deploy-plugins.yml
    with:
      ARTIFACT_NAME: ${{inputs.PLUGINS_ARTIFACT_NAME}}
      DEPLOYMENT_NAME: ${{needs.deploy-infra.outputs.deployment-id}}
      ENVIRONMENT: ${{inputs.ENVIRONMENT}}
